credentials-email
crazyantlabs/sftptogo-docs pull request #184
Opened 2024-11-28 13:49 UTC by saggineumann

2024-11-28 15:23 UTC, motymichaely requested changes
@saggineumann I left a few comments and change suggestions.

2024-11-28 15:23 UTC, motymichaely commented on docs/getting-started/dashboard.md
> +2. Add, edit, seasrch or remove credentials.
```suggestion
2. Add, edit, search or remove credentials.
```

2024-11-28 15:23 UTC, motymichaely commented on docs/getting-started/dashboard.md
> +3. Manage access options for credentials (home directories, permissions, public keys, inbound network rules, passwords and email association).
```suggestion
3. Manage access options for credentials (home directories, permissions, public keys, inbound network rules, passwords and email associations).
```

2024-11-28 15:23 UTC, motymichaely commented on docs/getting-started/organization-settings.md
> +* Magic Code - Identification based on username and unique, six character long, one-time-use codes, sent to the email address associated with the username. This form of authentication is only support
```suggestion
* Magic Code - identification based on username and a unique, six character one-time-use code sent to the email address associated with the username. This form of authentication is only supported by the web portal.
```

2024-11-28 15:23 UTC, motymichaely commented on docs/how-to-connect/connect-web-portal.md
> +3. Click the "Log in" button.
```suggestion
3. Click the "Sign in" button.
```

2024-11-28 15:23 UTC, motymichaely commented on docs/how-to-connect/connect-web-portal.md
> +2. Enter a credentials password (or magic code if the credentials are associated with an email address and the [Magic Code](../getting-started/organization-settings#authentication-methods). authentic
```suggestion
2. Enter a credentials password or click "Email sign-in code" if the credentials are associated with an email address and the [Magic Code](../getting-started/organization-settings#authentication-methods) authentication method is enabled).
```

2024-11-28 16:05 UTC, saggineumann commented
Thanks @motymichaely - all of your changes look good

2024-12-01 10:02 UTC, motymichaely approved these changes

2024-12-01 10:03 UTC, merged